#ros2 node for controller manager
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    #topic for broadcasting joint states
    joint_state_broadcaster:
      # From ros2_controllers repo, joint_state_broadcaster pkg
      type: joint_state_broadcaster/JointStateBroadcaster
   
    #topic for velocity controller
    simple_velocity_controller:
      #From ros2_controllers repo, velocity_controllers pkg
      type: velocity_controllers/JointGroupVelocityController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
     
        

#ros2 node for velocity controller
simple_velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    
diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: [left_wheel_joint]
    right_wheel_names: [right_wheel_joint]
    publish_rate: 50 
    pose_convariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_convariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_radius: 0.1905
    wheel_separation: 0.7747
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.0

    cmd_vel_timeout: 0.25
    base_frame_id: base_link
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 0.8
        min_accceleration: 0.4
        has_jerk_limits: false

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.7
        min_velocity: -1.7
        has_acceleration_limits: true
        max_acceleration: 1.5
        min_acceleration: -1.0
        has_jerk_limits: false

   
    
        

