joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: diff_drive_controller/cmd_vel
      deadman_buttons: [3]
      value:
        linear:
          x: 0.0
          y: 0.0
          z: 0.0
        angular:
          x: 0.0
          y: 0.0
          z: 0.0
      axis_mappings:
        twist-linear-x:
          axis: 1
          scale: 2.0
          offset: 0.0
          deadman: true
        twist-angular-z:
          axis: 3
          scale: 4.0
          offset: 0.0
          deadman: true
  
